name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: dendrite-demo-pinecone
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
    - run: nix build .#dockerImage
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u bbigras --password-stdin
    - run: ./result | gzip | nix run nixpkgs#skopeo -- --insecure-policy copy docker-archive:/dev/stdin docker://ghcr.io/bbigras/dendrite-demo-pinecone
      if: ${{ github.event_name == 'push' }}
