{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v18",
          "with": {
            "extra_nix_config": "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
          }
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v12",
          "with": {
            "name": "dendrite-demo-pinecone",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix build"
        },
        {
          "name": "Generate docker image script",
          "run": "nix build .#dockerImage"
        },
        {
          "name": "Log in to ghcr.io",
          "run": "echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u bbigras --password-stdin"
        },
        {
          "name": "Build and push image",
          "run": "./result | gzip | nix run nixpkgs#skopeo -- --insecure-policy copy docker-archive:/dev/stdin docker://ghcr.io/bbigras/dendrite-demo-pinecone"
        }
      ]
    }
  }
}
