{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2.3.4"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v13",
          "with": {
            "install_url": "https://nixos-nix-install-tests.cachix.org/serve/sp832rai317zyw7ikhlzv454zh9qr3dv/install",
            "install_options": "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve",
            "extra_nix_config": "experimental-features = nix-command flakes ca-derivations ca-references"
          }
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v10",
          "with": {
            "name": "dendrite-demo-pinecone",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "Build",
          "run": "nix build"
        },
        {
          "name": "Build docker image",
          "run": "nix build .#dockerImage"
        },
        {
          "name": "Load docker image",
          "run": "docker load < ./result"
        },
        {
          "name": "Tag docker image",
          "run": "docker tag dendrite-demo-pinecone bbigras/dendrite-demo-pinecone"
        },
        {
          "name": "Log in to Docker Hub",
          "uses": "docker/login-action@v1",
          "with": {
            "username": "${{ secrets.DOCKER_USERNAME }}",
            "password": "${{ secrets.DOCKER_PASSWORD }}"
          }
        },
        {
          "name": "Push to Docker Hub",
          "run": "docker push bbigras/dendrite-demo-pinecone"
        }
      ]
    }
  }
}
