name: update flakes
on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: 'nixpkgs=channel:nixos-unstable'
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - uses: cachix/cachix-action@v12
        with:
          name: dendrite-demo-pinecone
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: git config --global user.email "noreply@github.com"
      - run: git config --global user.name "GitHub"
      - name: Update flakes
        run: nix flake update --commit-lock-file
      - name: Update vendorSha256
        run: ./update.sh
      - name: git commit (amend)
        run: git commit --amend --no-edit
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: flake-update
          commit-message: "flake: update"
          delete-branch: true
          title: "flake: update"
