name: Update niv

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v10
      with:
        name: nix-matrix-pinecone
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cachix use niv
    - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} nix run '((import (import ./nix/sources.nix).niv {}).niv)' -c niv update
    - run: nix run '((import (import ./nix/sources.nix).nixpkgs {}).nix-build-uncached)' -c nix-build-uncached
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
