name: update flakes
on:
  schedule:
    - cron:  '* */6 * * *'
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          nix_path: 'nixpkgs=channel:nixos-unstable'
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: dendrite-demo-pinecone
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: git config --global user.email "noreply@github.com"
      - run: git config --global user.name "GitHub"
      - name: Update flakes
        run: nix flake update --commit-lock-file
      - name: Update vendorSha256
        run: ./update.sh
      - name: git commit (amend)
        run: git commit --amend --no-edit
      - uses: peter-evans/create-pull-request@v3.12.1
        with:
          branch: flake-update
          commit-message: "flake: update"
          delete-branch: true
          title: "flake: update"
